### ISSUE TITLE
Back button presente na tela de unidade de manutenção

### ISSUE THREAD

**Issue by phenome** [wwmm/sostecsaude#4]
![image](https://user-images.githubusercontent.com/360894/79671225-d6764300-81c0-11ea-8a95-737b476b814b.png)
Por enquanto só há uma atividade. Ao apertar o botão retornamos à mesma atividade.

**Comment by wwmm** [comment]
Tem um tempo que estou de tentar resolver isso. Amanhã dou uma olhada.

**Comment by wwmm** [comment]
No fim resolvi configurando o título da titlebar manualmente. Foi mais fácil que convencer o navigation controller a tirar o back button XD
